#!/usr/bin/env python3
"""
端到端验证工具 — 证明 LOG_* → LOG_PURE 变换无损。

流程:
  1. 扫描所有 LOG_* 调用, 提取 (module, level, fmt, 参数表达式)
  2. 为每个唯一调用生成 test_xxx() → 调用宏 + 写入 baseline 文件
  3. 编译原始项目 → 运行 → 捕获 baseline (spdlog 输出)
  4. 运行 log_transform.py 变换
  5. 编译变换项目 → 运行 → 捕获 pure.log
  6. 用 log_restore.py 还原 → diff baseline
  7. 输出: PASSED (zero diff) 或 FAILED (diff 详情)

用法:
  python tools/log_validate.py [--keep-temp] [--out /tmp/validate]

输出:
  All 421 calls PASSED — 0 diffs
"""

import os, sys, json, hashlib, shutil, subprocess, re, argparse, tempfile
from pathlib import Path
from collections import defaultdict

# ---- 复用 log_transform.py 的核心函数 ----
_STR_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')

# ---- 阶段 1: 扫描 ----

def scan_log_calls(proj_dir: str) -> list[dict]:
    """扫描项目下所有 LOG_* 调用, 去重返回唯一列表。
    每个元素: {file, line, macro, module, level, fmt, args_expr}
    """
    _MACRO_RE = re.compile(
        r'\b(LOG_[A-Z_]+?_(?:TRACE|DEBUG|INFO|WARN|ERROR|CRITICAL))\s*\('
    )
    _ML_RE = re.compile(r'^LOG_([A-Z_]+?)_(TRACE|DEBUG|INFO|WARN|ERROR|CRITICAL)$')

    seen = set()
    calls = []

    for root, dirs, files in os.walk(proj_dir):
        dirs[:] = [d for d in dirs if not d.startswith('build') and not d.startswith('.')]
        for fname in files:
            ext = os.path.splitext(fname)[1].lower()
            if ext not in {'.cpp', '.h', '.hpp', '.cc', '.tpp'}:
                continue
            fpath = os.path.join(root, fname)
            try:
                with open(fpath, encoding='utf-8', errors='replace') as f:
                    text = f.read()
            except Exception:
                continue

            for m in _MACRO_RE.finditer(text):
                macro = m.group(1)
                ml = _ML_RE.match(macro)
                if not ml:
                    continue
                module, level = ml.group(1), ml.group(2)

                # 括号计数找闭括号
                paren_start = m.end() - 1
                i, depth = paren_start + 1, 1
                while i < len(text) and depth > 0:
                    if text[i] == '(': depth += 1
                    elif text[i] == ')': depth -= 1
                    i += 1
                if depth != 0:
                    continue
                call_body = text[paren_start + 1:i - 1]

                sm = _STR_RE.search(call_body)
                if not sm:
                    continue
                import codecs
                try:
                    fmt_str = codecs.decode(sm.group(1), 'unicode_escape')
                except Exception:
                    fmt_str = sm.group(1)

                # 提取参数表达式
                args_start = sm.end()
                while args_start < len(call_body) and call_body[args_start] in (' ', '\t', '\n'):
                    args_start += 1
                if args_start < len(call_body) and call_body[args_start] == ',':
                    args_start += 1
                args_expr = call_body[args_start:].strip()

                # 去重: 相同 (module, level, fmt) 只保留一个
                key = (module, level, fmt_str)
                if key not in seen:
                    seen.add(key)
                    line = text[:m.start()].count('\n') + 1
                    rel = os.path.relpath(fpath, proj_dir)
                    calls.append({
                        'file': rel, 'line': line,
                        'macro': macro, 'module': module, 'level': level,
                        'fmt': fmt_str, 'args_expr': args_expr,
                    })

    return calls


# ---- 阶段 2: 生成测试文件 ----

def generate_test_file(calls: list[dict], out_path: str):
    """为所有调用生成 C++ 测试文件。"""
    lines = [
        '#include <cstdio>',
        '#include <cstdlib>',
        '#include <cstring>',
        '#include <string>',
        '#include <chrono>',
        '#include "mail_system/back/common/logger.h"',
        '',
        '// Auto-generated by log_validate.py',
        '// Validates ALL log calls produce identical output after LOG_PURE round-trip',
        '',
        'static FILE* g_baseline = nullptr;',
        '',
        'void write_baseline(const char* str) {',
        '    if (g_baseline) {',
        '        fputs(str, g_baseline);',
        '        fputc(\'\\n\', g_baseline);',
        '        fflush(g_baseline);',
        '    }',
        '}',
        '',
    ]

    # 生成占位值函数, 模拟各种参数类型
    lines.append('// ---- 参数值生成器 (覆盖常见类型) ----')
    lines.append('template<typename T> T make_val(int n) { return T{}; }')
    lines.append('template<> int make_val(int n) { return 100 + n % 900; }')
    lines.append('template<> unsigned make_val(int n) { return 200 + n % 800; }')
    lines.append('template<> long make_val(int n) { return 300 + n % 700; }')
    lines.append('template<> unsigned long make_val(int n) { return 400 + n % 600; }')
    lines.append('template<> size_t make_val(int n) { return 1 + n % 99; }')
    lines.append('template<> double make_val(int n) { return 3.14 + n * 0.1; }')
    lines.append('template<> float make_val(int n) { return 2.71f + n * 0.1f; }')
    lines.append('template<> bool make_val(int n) { return n % 2 == 0; }')
    lines.append('template<> const char* make_val(int n) {')
    lines.append('    static const char* vals[] = {"alpha","beta","gamma","delta","epsilon","zeta","eta","theta"};')
    lines.append('    return vals[n % 8];')
    lines.append('}')
    lines.append('template<> std::string make_val(int n) { return std::string("str_") + char(\'a\' + n % 26); }')
    lines.append('')

    # 为每个唯一的 (module, level, fmt) 生成测试函数
    lines.append('// ---- 测试函数 ----')
    for idx, call in enumerate(calls):
        fmt = call['fmt']
        n_args = fmt.count('{}')
        # 计算参数类型: 如果有原始 args_expr, 尝试推断类型; 否则用 string
        arg_types = _infer_types(call['args_expr']) if call['args_expr'] and n_args > 0 else ['const char*'] * n_args

        # 生成参数的占位值
        arg_list = []
        for a in range(n_args):
            t = arg_types[a] if a < len(arg_types) else 'const char*'
            arg_list.append(f'make_val<{t}>({a})')

        lines.append(f'// [{idx}] {call["module"]}::{call["level"]}  {call["file"]}:{call["line"]}')
        lines.append(f'void test_{idx:04d}() {{')

        if len(arg_list) == 1:
            arg_str = arg_list[0]
        elif arg_list:
            arg_str = ', '.join(arg_list)
        else:
            arg_str = ''

        lines.append(f'    {call["macro"]}("{fmt}", {arg_str});')
        lines.append(f'}}')
        lines.append('')

    # 主函数: 初始化 spdlog, 运行所有测试
    lines.append('int main() {')
    lines.append('    g_baseline = fopen("baseline.log", "w");')
    lines.append('    if (!g_baseline) return 1;')
    lines.append('')
    lines.append('    mail_system::Logger::get_instance().init(')
    lines.append('        "logs/test_smtps.log", 1024*1024*5, 3,')
    lines.append('        spdlog::level::info, false, true);')
    lines.append('')

    for idx in range(len(calls)):
        lines.append(f'    test_{idx:04d}();')

    lines.append('')
    lines.append('    mail_system::log_pure_flush();')
    lines.append('    mail_system::Logger::get_instance().shutdown();')
    lines.append('    fclose(g_baseline);')
    lines.append('    return 0;')
    lines.append('}')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))


def _infer_types(expr: str) -> list[str]:
    """从参数表达式列表粗略推断类型。"""
    types = []
    for arg in expr.split(','):
        arg = arg.strip()
        if not arg:
            continue
        # 常见模式
        if any(kw in arg for kw in ['size()', 'length()', 'count()', 'size_t']):
            types.append('size_t')
        elif any(kw in arg.lower() for kw in ['.find(', '.substr(', 'c_str(', 'string']):
            types.append('std::string')
        elif 'true' in arg or 'false' in arg:
            types.append('bool')
        elif arg.replace('.', '').replace('-', '').isdigit():
            types.append('int')
        elif arg.startswith('"'):
            types.append('const char*')
        else:
            types.append('const char*')
    return types


# ---- 阶段 3-6: 构建、运行、对比 ----

def run_cmd(cmd, cwd=None, capture=True):
    """运行命令, 返回 (returncode, stdout, stderr)"""
    kwargs = {}
    if capture:
        kwargs['capture_output'] = True
        kwargs['text'] = True
    if cwd:
        kwargs['cwd'] = cwd
    r = subprocess.run(cmd, **kwargs)
    return r.returncode, r.stdout or '', r.stderr or ''


def validate(proj_dir: str, work_dir: str) -> tuple[bool, str]:
    """完整验证流程。返回 (成功, 摘要)。"""
    # ---- Step 1: 扫描 ----
    print("Step 1/6: Scanning LOG_* calls ...")
    calls = scan_log_calls(proj_dir)
    print(f"  Found {len(calls)} unique log templates")

    # ---- Step 2: 生成测试文件 ----
    print("Step 2/6: Generating test file ...")
    test_cpp = os.path.join(work_dir, 'log_validate_test.cpp')
    generate_test_file(calls, test_cpp)
    print(f"  Generated {test_cpp} ({len(calls)} test functions)")

    # ---- Step 3: Baseline (原始代码) ----
    print("Step 3/6: Building baseline (original spdlog) ...")
    # 拷贝项目 + 测试文件
    baseline_dir = os.path.join(work_dir, 'baseline')
    shutil.copytree(proj_dir, baseline_dir,
                    ignore=shutil.ignore_patterns('build', '.git', '__pycache__', 'logs', '*.log'),
                    dirs_exist_ok=True)

    # 写 CMakeLists.txt 来构建测试
    cmake_content = f'''cmake_minimum_required(VERSION 3.10)
project(LogValidate LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
include_directories("${{CMAKE_SOURCE_DIR}}/include")
include_directories("/opt/homebrew/include")
# Minimal: only link spdlog + fmt
find_package(spdlog REQUIRED)
add_executable(log_validate log_validate_test.cpp)
target_link_libraries(log_validate spdlog::spdlog)
'''
    with open(os.path.join(baseline_dir, 'CMakeLists.txt'), 'w') as f:
        f.write(cmake_content)

    # 构建 baseline
    ret, out, err = run_cmd(
        ['cmake', '-B', 'build', '-S', baseline_dir, '-DCMAKE_BUILD_TYPE=Release'],
        cwd=work_dir)
    if ret != 0:
        return False, f"baseline cmake configure failed:\n{err[:500]}"

    ret, out, err = run_cmd(
        ['cmake', '--build', 'build', '--parallel'],
        cwd=work_dir)
    if ret != 0:
        return False, f"baseline build failed:\n{err[:500]}"

    # 运行 baseline
    ret, out, err = run_cmd(
        [os.path.join(work_dir, 'build', 'log_validate')],
        cwd=work_dir)
    baseline_log = os.path.join(work_dir, 'baseline.log')

    # 读取 baseline (从 spdlog 文件输出提取)
    # 因为 LOG_* 会同时输出到文件和控制台, 我们捕获文件输出
    spdlog_file = os.path.join(work_dir, 'logs', 'test_smtps.log')
    if os.path.exists(spdlog_file):
        with open(spdlog_file) as f:
            baseline_lines = f.readlines()
    else:
        baseline_lines = []
    print(f"  Baseline: {len(baseline_lines)} log lines")

    # ---- Step 4: Transform + build structured ----
    print("Step 4/6: Transforming LOG_* → LOG_PURE ...")
    struct_dir = os.path.join(work_dir, 'structured')
    # 用 log_transform.py 变换
    transform_script = os.path.join(proj_dir, 'tools', 'log_transform.py')
    if not os.path.exists(transform_script):
        transform_script = os.path.join(os.path.dirname(__file__), 'log_transform.py')

    ret, out, err = run_cmd(
        ['python3', transform_script, baseline_dir, '--out', struct_dir],
        capture=False)
    if ret != 0:
        return False, f"transform failed"

    # 构建 structured 版本
    ret, out, err = run_cmd(
        ['cmake', '-B', 'build_s', '-S', struct_dir, '-DCMAKE_BUILD_TYPE=Release',
         '-DCMAKE_CXX_FLAGS=-I/opt/homebrew/include'],
        cwd=work_dir)
    if ret != 0:
        return False, f"structured cmake failed:\n{err[:500]}"

    ret, out, err = run_cmd(
        ['cmake', '--build', 'build_s', '--parallel'],
        cwd=work_dir)
    if ret != 0:
        return False, f"structured build failed:\n{err[:500]}"

    # 运行 structured
    ret, out, err = run_cmd(
        [os.path.join(work_dir, 'build_s', 'log_validate')],
        cwd=work_dir)
    pure_log = os.path.join(work_dir, 'logs', 'pure.log')

    # ---- Step 5: Restore ----
    print("Step 5/6: Restoring pure.log ...")
    restore_script = os.path.join(proj_dir, 'tools', 'log_restore.py')
    map_file = os.path.join(work_dir, 'logs', 'pure_map.json')
    if not os.path.exists(map_file):
        map_file = os.path.join(struct_dir, 'logs', 'pure_map.json')
    restored_log = os.path.join(work_dir, 'restored.log')

    if not os.path.exists(pure_log):
        return False, f"pure.log not found at {pure_log}"

    ret, out, err = run_cmd(
        ['python3', restore_script, pure_log, '--map', map_file, '--out', restored_log])
    if ret != 0:
        return False, f"restore failed:\n{err[:500]}"

    # ---- Step 6: Diff ----
    print("Step 6/6: Comparing baseline vs restored ...")

    # 提取 baseline 的消息体 (去掉 spdlog 的 [时间][级别][线程][模块] 前缀)
    baseline_msgs = [_extract_msg(line) for line in baseline_lines]
    baseline_msgs = [m for m in baseline_msgs if m]

    with open(restored_log) as f:
        restored_msgs = [_extract_msg(line) for line in f if line.strip()]
    restored_msgs = [m for m in restored_msgs if m]

    diffs = []
    for i, (b, r) in enumerate(zip(baseline_msgs, restored_msgs)):
        if b != r:
            diffs.append((i, b, r))

    # 数量不一致
    if len(baseline_msgs) != len(restored_msgs):
        diffs.append((-1,
            f"count: baseline={len(baseline_msgs)}",
            f"count: restored={len(restored_msgs)}"))

    if diffs:
        report = ["FAILED — diffs found:"]
        for i, b, r in diffs[:10]:
            report.append(f"  #{i}:")
            report.append(f"    baseline: {b[:120]}")
            report.append(f"    restored: {r[:120]}")
        return False, '\n'.join(report)

    return True, f"All {len(baseline_msgs)} log calls PASSED — zero diffs"


def _extract_msg(line: str) -> str:
    """从日志行提取消息体 (去掉 prefix)"""
    line = line.strip()
    if not line:
        return ''
    # spdlog 格式: [时间] [级别] [线程] [模块] ...  消息
    # LOG_PURE 还原格式: [时间] [级别][模块] 消息
    # 提取最后一个 ] 之后的内容
    idx = line.rfind('] ')
    if idx >= 0:
        return line[idx + 2:]
    return line


def main():
    parser = argparse.ArgumentParser(description='E2E validation for LOG_* → LOG_PURE')
    parser.add_argument('project_dir', nargs='?', default='.',
                        help='项目根目录')
    parser.add_argument('--out', default=None,
                        help='工作目录 (默认: /tmp/log_validate_<timestamp>)')
    parser.add_argument('--keep', action='store_true',
                        help='保留临时文件')
    args = parser.parse_args()

    proj = os.path.abspath(args.project_dir)
    work = args.out or tempfile.mkdtemp(prefix='log_validate_')

    os.makedirs(work, exist_ok=True)

    ok, report = validate(proj, work)

    print("\n" + "=" * 60)
    print(report)

    if not args.keep and args.out is None:
        shutil.rmtree(work, ignore_errors=True)
    elif ok:
        print(f"\nTemp files kept at: {work}")

    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
